volumes:
  postgres_data:

services:
  postgres:
    image: postgres:13.3
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./bot_backend/
    env_file: .env
    depends_on:
      - postgres